# Generated by Django 3.0a1 on 2020-01-12 14:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0003_food_frestaurant'),
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='cart',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('qty', models.IntegerField()),
                ('food', models.ManyToManyField(to='app1.food')),
            ],
        ),
        migrations.AddField(
            model_name='customuser',
            name='ucart',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='users.cart'),
        ),
    ]
