# Generated by Django 3.0a1 on 2020-01-12 14:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0004_foodpair'),
        ('users', '0002_auto_20200112_1945'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cart',
            name='food',
        ),
        migrations.RemoveField(
            model_name='cart',
            name='qty',
        ),
        migrations.AddField(
            model_name='cart',
            name='foodp',
            field=models.ManyToManyField(to='app1.foodpair'),
        ),
    ]
