# Generated by Django 2.2.6 on 2020-01-22 10:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_cart_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cart',
            name='foodp',
            field=models.ManyToManyField(blank=True, null=True, to='app1.foodpair'),
        ),
    ]
