# Generated by Django 3.0.2 on 2020-01-26 11:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0011_auto_20200122_1617'),
        ('users', '0006_cart_tot'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cart',
            name='foodp',
            field=models.ManyToManyField(blank=True, to='app1.foodpair'),
        ),
    ]
