# Generated by Django 3.0a1 on 2020-01-12 13:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='food',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fname', models.CharField(max_length=250)),
                ('fmoney', models.IntegerField()),
                ('fimg', models.ImageField(upload_to='media/food')),
                ('frating', models.DecimalField(decimal_places=1, max_digits=5)),
            ],
        ),
        migrations.CreateModel(
            name='restaurant',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rname', models.CharField(max_length=250)),
                ('rphone', models.BigIntegerField()),
                ('rrating', models.DecimalField(decimal_places=1, max_digits=5)),
                ('cuisine', models.TextField(default='')),
                ('rimg', models.ImageField(upload_to='media/restaurant')),
            ],
        ),
        migrations.CreateModel(
            name='fcat',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cname', models.CharField(max_length=250)),
                ('food', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app1.food')),
            ],
        ),
    ]
