# Generated by Django 3.0a1 on 2020-01-12 13:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='fcat',
            name='food',
        ),
        migrations.AddField(
            model_name='food',
            name='fcat',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='app1.fcat'),
        ),
    ]
