# Generated by Django 3.0a1 on 2020-01-12 14:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0002_auto_20200112_1918'),
    ]

    operations = [
        migrations.AddField(
            model_name='food',
            name='frestaurant',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='app1.restaurant'),
        ),
    ]
