# Generated by Django 3.0a1 on 2020-01-12 14:30

import django.core.validators
from django.db import migrations, models
import phone_field.models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0004_foodpair'),
    ]

    operations = [
        migrations.AlterField(
            model_name='food',
            name='fmoney',
            field=models.IntegerField(default=0, validators=[django.core.validators.MinValueValidator(0)]),
        ),
        migrations.AlterField(
            model_name='foodpair',
            name='qty',
            field=models.IntegerField(default=0, validators=[django.core.validators.MinValueValidator(0)]),
        ),
        migrations.AlterField(
            model_name='restaurant',
            name='rphone',
            field=phone_field.models.PhoneField(max_length=31, unique=True),
        ),
    ]
