# Generated by Django 3.0a1 on 2020-01-16 13:54

from django.db import migrations
import phonenumber_field.modelfields


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0006_auto_20200112_2003'),
    ]

    operations = [
        migrations.AlterField(
            model_name='restaurant',
            name='rphone',
            field=phonenumber_field.modelfields.PhoneNumberField(max_length=128, region=None, unique=True),
        ),
    ]
