# Generated by Django 2.2.6 on 2020-01-20 18:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0008_food_fnum'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='food',
            name='fnum',
        ),
    ]
