# Generated by Django 2.2.6 on 2020-01-22 10:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0009_remove_food_fnum'),
    ]

    operations = [
        migrations.AlterField(
            model_name='food',
            name='fimg',
            field=models.ImageField(upload_to='food/'),
        ),
        migrations.AlterField(
            model_name='restaurant',
            name='rimg',
            field=models.ImageField(upload_to='restaurant/'),
        ),
    ]
