# Generated by Django 2.2.6 on 2020-01-22 10:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0010_auto_20200122_1543'),
    ]

    operations = [
        migrations.AlterField(
            model_name='food',
            name='fimg',
            field=models.ImageField(blank=True, null=True, upload_to='food/'),
        ),
    ]
