# Generated by Django 3.0.2 on 2020-01-26 21:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0012_auto_20200127_0218'),
    ]

    operations = [
        migrations.AlterField(
            model_name='foodpair',
            name='food',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='app1.food'),
        ),
    ]
